version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: oxen_mysql
    environment:
      MYSQL_ROOT_PASSWORD: oxenorm
      MYSQL_DATABASE: oxenorm
      MYSQL_USER: oxenorm
      MYSQL_PASSWORD: oxenorm
    ports:
      - '3306:3306'
    command: [--default-authentication-plugin=mysql_native_password, --max_connections=200]
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-uoxenorm', '-poxenorm']
      interval: 5s
      timeout: 5s
      retries: 20
